#!/bin/sh
set -eu

case "${1}" in
  purge)
    rm -f /etc/konnector.env
    rm -f /etc/sudoers.d/konnector-deploy
    ;;
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
  *)
    echo "postrm called with unknown argument: ${1}" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
