#!/bin/sh
set -eu

case "${1}" in
  configure)
    /usr/bin/konnector init
    ;;
  abort-upgrade|abort-remove|abort-deconfigure)
    ;;
  *)
    echo "postinst called with unknown argument: ${1}" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
